//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreSquid.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiniLeagueFixture
    {
        public MiniLeagueFixture()
        {
            this.Fixtures = new HashSet<Fixture>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Fixture> Fixtures { get; set; }
        public virtual MiniLeague MiniLeague { get; set; }
    }
}
