//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreSquid.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public Score()
        {
            this.Players = new HashSet<Player>();
        }
    
        public int Id { get; set; }
        public int WeekScore { get; set; }
        public int MonthScore { get; set; }
        public int TotalScore { get; set; }
    
        public virtual ICollection<Player> Players { get; set; }
    }
}
